"""Add learning_duration to User model

Revision ID: be074cf3578a
Revises: 43733f1bc946
Create Date: 2025-07-12 16:22:21.268309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be074cf3578a'
down_revision = '43733f1bc946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('learning_duration')

    # ### end Alembic commands ###
